[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.10.1"
jupyterlab = "^4.3.6"
jupyterlab-rise = "^0.43.1"
jupytext = "^1.16.7"
dyalog-jupyter-kernel = "^2.0.2"
py-n-apl = {git = "https://github.com/Dyalog/pynapl"}
